# ########################### #
# 当前文件中的是【开发环境】的配置 #
# ########################### #

# 连接数据库的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_ams?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Web服务端口
server:
  port: 9081

# 日志的显示级别
logging:
  level:
    cn.tedu.csmall: trace

# 当前项目中的自定义配置
csmall:
  # JWT相关配置
  jwt:
    # 生成和解析JWT时使用的secretKey，此属性的值不得少于4个字符，建议在30~60字符之间，应该是一个不容易被猜测的值
    secret-key: fdsFOj4tp9Dgvfd9t45rDkFSLKgfR8ou
    # 【新增】JWT的有效时长，以分钟为单位
    duration-in-minute: 100800000